### PR TITLE
Default Hatsune Miku Mod

### PR DESCRIPTION
**Pull request by JanexLane**

### CODE REVIEW

**Comment by PapaSmurf-ML64** [comment]
Please place your zobj files in a folder and prefix your pak with "Adult_", "Child_", or "Combined_" as applies.

**Comment by JanexLane** [comment]
I did it I think

**Comment by Highlander1536** [comment]
👀

**Comment by PapaSmurf-ML64** [comment]
Was gonna merge this and manually fix the files, but child model soft locks.

**Pull request closed without merging**
